import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { MutableRefObject, useEffect, useRef, useState } from 'react'
import { Game } from '../models/Game'
import { gameSettings } from '../models'

export default function Home() {

    const canvasRef = useRef() as MutableRefObject<HTMLCanvasElement>

    useEffect(() => {
        const canvas = canvasRef.current

        // 16 = width   aspectRatio = width
        //  9 = height                height
        const aspectRatio = 16 / 9

        canvas.width = innerWidth * .8
        canvas.height = canvas.width / aspectRatio


        gameSettings.canvas = canvas
        gameSettings.ctx = canvas.getContext("2d")

        let game = new Game()

        const audio = new Audio()
        audio.src = "/sounds/background.mp3"
        audio.volume = .08
        audio.loop = true
        let audioStarted = false
        const animate = () => {
            requestAnimationFrame(animate)

            if (!audioStarted && game.input.keys.length !== 0) audio.play()
            if (game.isGameEnded) audio.pause()

            gameSettings.ctx!.fillStyle = "black"
            gameSettings.ctx!.fillRect(0, 0, canvas.width, canvas.height)
            game.update()
            game.draw()


            if (game.isGameEnded && game.input.keys.includes("KeyR")) {
                game = new Game()
                gameSettings.enemiesKilled = 0
                gameSettings.score = 0
            }
        }

        animate()
    }, [])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <canvas className={styles.canvas} ref={canvasRef}></canvas>
            </main>
        </>
    )
}
